#### general settings
name: PANx3_merged_filtered_even_data_finetune_sharp_100000
use_tb_logger: True
model: sr
distortion: sr
scale: 3
save_img: False
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: even_merged
    mode: LQGT
    dataroot_GT: /home/user/iron_swords/face_detection_superresolution/PAN/datasets/even_merged_extracted/merged_filtered_even_data_train_sharp
    dataroot_LQ: /home/user/iron_swords/face_detection_superresolution/PAN/datasets/even_merged_extracted/merged_filtered_even_data_train_lr_3_sharp
    
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 216
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: even_merged
    mode: LQGT
    dataroot_GT: /home/user/iron_swords/face_detection_superresolution/PAN/datasets/even_merged/merged_filtered_even_data_val
    dataroot_LQ: /home/user/iron_swords/face_detection_superresolution/PAN/datasets/even_merged/merged_filtered_even_data_val_lr_4

#### network structures
network_G:
  which_model_G: PAN
  in_nc: 3
  out_nc: 3
  nf: 40
  unf: 24
  nb: 16
  scale: 3
  
#### path
path:
  pretrain_model_G: /home/user/iron_swords/face_detection_superresolution/PAN/experiments/pretrained_models/PANx3_DF2K.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 7e-5
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 100000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 10000e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
